name: Build
on:
  push:
    branches: [main, master]
  pull_request:
jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: '3.30'
      
      - name: Use cmake
        run: cmake --version
        
      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v2
        with:
          version: "20.1.4"



      - name: Configure
        run: cmake --preset default

      - name: Build
        run: cmake --build --preset default